name: 'Adminify'
author: [ThatJavaGuy, CainFoool]
version: 1.0
main: com.cainkilgore.adminify.Adminify
commands:
   freeze:
       description: 'Freeze/Unfreeze a player in their spot'
       usage: /<command> <player>
   tp:
       description: 'Teleport you/another player to another'
       usage: /<command> <[player] <player>> <[x] [y] [z]>
   spawn:
       description: 'Teleport you/another player to world spawn'
       usage: /<command> <player>
   mute:
       description: 'Mute players from using chat'
       usage: /<command> <player>
   fly:
       description: 'Set yours/others ability to fly'
       usage: /<command> <player>
   god:
       description: 'Enable yours/others god mode'
       usage: /<command> <player>
   adminify:
       description: 'Basic Information'
       usage: /<command>
   time:
       description: 'Change the time of the world'
       usage: /<command> <day/night>
   heal:
       description: 'Heal yourself/another player to max health'
       usage: /<command> <player>
   hit:
       description: 'Damage a player with a random value'
       usage: /<command> [player]
   clear:
       description: 'Clear yours/anothers inventory'
       usage: /<command> <player>
   kill:
       description: 'Kill yourself or another'
       usage: /<command> <player>
   vanish:
       description: 'Hide/show yourself to all players'
       usage: /<command>
   alert:
       description: 'Send a Chat Alert'
       usage: /<command> <alert>
   lastpos:
       description: 'Teleport to yours/another players last location'
       usage: /<command> <player>
   strike:
       description: 'Strike a player with lightning'
       usage: /<command> [player]
   home:
       description: 'Teleport to your home'
       usage: /<command>
   sethome:
       description: 'Set your home destination'
       usage: /<command>
   msg:
       description: 'Send a message to a player privately'
       usage: /<command> [player] [message]
   spawnmob:
       description: 'Spawn a specified amount of entities at your cursor'
       usage: /<command> [?/entity] [count]
   tphere:
       description: 'Teleport a player to you'
       usage: /<command> <player>
   gm:
       description: 'Change yours/another players gamemode'
       usage: /<command> [s/c/a/0/1/2/survival/creative/adventure] <player>
   feed:
       description: 'Feed yourself or another'
       usage: /<command> <player>
   ride:
       description: 'Make two entities start riding'
       usage: /<command>
   setspawn:
       description: 'Set the current world spawn'
       usage: /<command>
   motd:
       description: 'Get the message of the day (showed on login)'
       usage: /<command>
   snowman:
       description: 'Toggle your snowman abilities'
       usage: /<command>