name: 'Adminify'
author: CainFool
version: 1.0
main: com.cainkilgore.adminify.Adminify
commands:
   freeze:
       description: 'Freeze/Unfreeze a player in their spot'
       usage: /<command> <player>