name: 'Adminify'
author: [ThatJavaGuy, CainFoool]
version: 1.0
main: com.cainkilgore.adminify.Adminify
commands:
   freeze:
       description: 'Freeze/Unfreeze a player in their spot'
       usage: /<command> <player>
   tp:
       description: 'Teleport you/another player to another'
       usage: /<command> <[player] <player>> <[x] [y] [z]>
   spawn:
       description: 'Teleport you/another player to world spawn'
       usage: /<command> <player>
   mute:
       description: 'Mute players from using chat'
       usage: /<command> <player>
   fly:
       description: 'Set yours/others ability to fly'
       usage: /<command> <player>
   god:
       description: 'Enable yours/others god mode'
       usage: /<command> <player>
   adminify:
       description: 'Basic Information'
       usage: /<command>
   time:
       description: 'Change the time of the world'
       usage: /<command> <day/night>
   heal:
       description: 'Heal yourself/another player to max health'
       usage: /<command> <player>
   hit:
       description: 'Damage a player with a random value'
       usage: /<command> [player]
   clear:
       description: 'Clear yours/anothers inventory'
       usage: /<command> <player>
   kill:
       description: 'Kill yourself or another'
       usage: /<command> <player>
   vanish:
       description: 'Hide/show yourself to all players'
       usage: /<command>
   alert:
       description: 'Send a Chat Alert'
       usage: /<command> <alert>
   lastpos:
       description: 'Teleport to yours/another players last location'
       usage: /<command> <player>
   strike:
       description: 'Strike a player with lightning'
       usage: /<command> [player]
   home:
       description: 'Teleport to your home'
       usage: /<command>
   sethome:
       description: 'Set your home destination'
       usage: /<command>