name: 'Adminify'
author: [ThatJavaGuy, CainFoool]
version: 1.0
main: com.cainkilgore.adminify.Adminify
commands:
   freeze:
       description: 'Freeze/Unfreeze a player in their spot'
       usage: /<command> <player>
   tp:
       description: 'Teleport you/another player to another'
       usage: /<command> [player] <player>
   spawn:
       description: 'Teleport you/another player to world spawn'
       usage: /<command> <player>
   mute:
       description: 'Mute players from using chat'
       usage: /<command> <player>
   fly:
       description: 'Set yours/others ability to fly'
       usage: /<command> <player>
   god:
       description: 'Enable yours/others god mode'
       usage: /<command> <player>
   adminify:
       description: 'Basic Information'
       usage: /<command>
   time:
       description: 'Change the time of the world'
       usage: /<command> <day/night>
   heal:
       description: 'Heal yourself/another player to max health'
       usage: /<command> <player>
   hit:
       description: 'Damage a player with a random value'
       usage: /<command> [player]