name: 'Adminify'
author: CainFool
version: 1.0
main: com.cainkilgore.adminify.Adminify
commands:
   freeze:
       description: 'Freeze/Unfreeze a player in their spot'
       usage: /<command> <player>
   tp:
       description: 'Teleport you/another player to another'
       usage: /<command> [player] <player>
   spawn:
       description: 'Teleport you/another player to world spawn'
       usage: /<command> <player>
   mute:
       description: 'Mute players from using chat'
       usage: /<command> <player>